import sharp from "sharp";
import { existsSync } from "node:fs";
import path from "node:path";

const SRC = "public/images/oficina/hero-rua-lareu.png";
const OUT_DIR = "public/images/oficina";
const BASENAME = "hero-rua-lareu";

if (!existsSync(SRC)) {
  console.error(`Source not found: ${SRC}`);
  process.exit(1);
}

const meta = await sharp(SRC).metadata();
console.log(`Source: ${meta.width}x${meta.height} ${meta.format}`);

// Cap largest output at source width — don't upscale
const MAX_WIDTHS = [Math.min(1920, meta.width), 1280, 960, 768];
const TARGETS = MAX_WIDTHS.map((w, i) => ({
  width: w,
  suffix: i === 0 ? "" : `-${w}`,
}));

for (const t of TARGETS) {
  const out = path.join(OUT_DIR, `${BASENAME}${t.suffix}.webp`);
  await sharp(SRC)
    .resize({ width: t.width, withoutEnlargement: true })
    .webp({ quality: 85, effort: 6 })
    .toFile(out);
  console.log(`  ${out}  (${t.width}w)`);
}

// Blur placeholder: 24px wide JPG file + base64 data URL for next/image
const blurOut = path.join(OUT_DIR, `${BASENAME}-blur.jpg`);
const blurBuffer = await sharp(SRC)
  .resize({ width: 24 })
  .jpeg({ quality: 40 })
  .toBuffer();
await (await import("node:fs/promises")).writeFile(blurOut, blurBuffer);
console.log(`  ${blurOut}  (24w blur)`);

const blurDataURL = `data:image/jpeg;base64,${blurBuffer.toString("base64")}`;
const blurModule = `// Auto-generated by scripts/optimize-hero.mjs — do not edit by hand.\nexport const HERO_BLUR_DATA_URL = ${JSON.stringify(blurDataURL)};\n`;
const modulePath = "src/lib/heroBlur.ts";
await (await import("node:fs/promises")).writeFile(modulePath, blurModule);
console.log(`  ${modulePath}  (blur data URL)`);

console.log("done.");
